title: s-note
description: 基于 Markdown 的轻量文档仓库，使用 GitHub Pages 托管
theme: minima
lang: zh-CN

url: "https://sschappy.github.io"
baseurl: "/s-note"

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty
